#!/bin/sh
### BEGIN INIT INFO
# Provides: Memlog
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 1
# Short-Description: periodic memory log
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="memlog"
DESC="Memlog"
PIDFILE=/var/run/memlog.pid
LOGFILE=/var/log/memlog.log

start_process() {
  touch $PIDFILE
  chmod a+w $PIDFILE
  # the log file gets only reset when restarting the service and could potentially fill up all the available disk space
  # don't care, it's about security challenges
  su -c "memlog c 30000 > $LOGFILE & echo \$! > $PIDFILE" root
}

stop_process() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start_process
    echo "done."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    stop_process
    echo "done."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    stop_process
    start_process
    echo "done."
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
exit 0
