#!/bin/sh
### BEGIN INIT INFO
# Provides: Logserver
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 1
# Short-Description: a vulnerable application
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="memlog"
DESC="Memlog"
PIDFILE=/var/run/memlog.pid

start_process() {
  touch $PIDFILE
  chmod a+w $PIDFILE
  #su -c "python3 /opt/webserver/webserver.py & echo \$! > $PIDFILE" webserveruser
}

stop_process() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start_process
    echo "done."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    stop_process
    echo "done."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    stop_process
    start_process
    echo "done."
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
exit 0
