#!/bin/sh
### BEGIN INIT INFO
# Provides: relaxed-rachel
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 1
# Short-Description: Simple FTP server
### END INIT INFO

PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
NAME="ftpserver"
DESC="FTP server"
PIDFILE=/var/run/pure-ftpd.pid

start_process() {
  touch $PIDFILE
  pure-ftpd & echo $! > $PIDFILE
}

stop_process() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start_process
    echo "done."
    ;;

  stop)
    echo -n "Stopping $DESC: "
    stop_process
    echo "done."
    ;;

  restart|force-reload)
    echo -n "Restarting $DESC: "
    stop_process
    start_process
    echo "done."
    ;;

  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
